#!/bin/sh
#
# disable probe

probe=$(( $1 -1 ))

if [ -f /sys/bus/i2c/devices/4-004$probe/iio:device*/in_active ]
then
      in_active=`ls /sys/bus/i2c/devices/4-004$probe/iio:device*/in_active`
      echo 0 > $in_active
fi
